import lang.stride.*;
import java.util.*;
import greenfoot.*;

public class ControlList extends World
{
    GreenfootSound gameSound;
    public ControlList()
    {
        super(990, 557, 1);
        prepare();
        gameSound = new GreenfootSound("GameplayMusic.wav");
    }
    
    public void started()
    {
        gameSound.playLoop();
    }
    
    public void stopped()
    {
        gameSound.stop();
    }

    private void prepare()
    {
       
   
       
       
        LeftKey leftKey = new LeftKey();
        addObject(leftKey,76,80);
        RightKey rightKey = new RightKey();
        addObject(rightKey,215,83);
        leftKey.setLocation(80,141);
        rightKey.setLocation(214,142);
        LeftAndRight leftAndRight = new LeftAndRight();
        addObject(leftAndRight,254,52);
        leftAndRight.setLocation(268,63);
        rightKey.setLocation(318,140);
        leftKey.setLocation(160,133);
        rightKey.setLocation(316,146);
        leftAndRight.setLocation(357,65);
        removeObject(leftAndRight);
        addObject(leftAndRight,276,53);
        leftAndRight.setLocation(372,64);
        rightKey.setLocation(336,144);
        leftAndRight.setLocation(126,60);
        leftKey.setLocation(124,115);
        rightKey.setLocation(299,127);
        rightKey.setLocation(328,153);
        leftKey.setLocation(127,144);
        Whirlpool whirlpool = new Whirlpool();
        addObject(whirlpool,882,457);
        rock rock = new rock();
        addObject(rock,822,317);
        Stone stone = new Stone();
        addObject(stone,887,314);
        Log log = new Log();
        addObject(log,842,253);
        stone.setLocation(908,299);
        GoldenCherry goldenCherry = new GoldenCherry();
        addObject(goldenCherry,723,106);
        Cherry cherry = new Cherry();
        addObject(cherry,799,104);
        Beaver beaver = new Beaver();
        addObject(beaver,212,142);
        beaver.setLocation(225,160);
        Piranha piranha = new Piranha();
        addObject(piranha,837,197);
        removeObject(beaver);
        removeObject(leftAndRight);
        removeObject(rightKey);
        removeObject(leftKey);
        LeftAndRight leftAndRight2 = new LeftAndRight();
        addObject(leftAndRight2,253,37);
        LeftKey leftKey2 = new LeftKey();
        addObject(leftKey2,112,120);
        RightKey rightKey2 = new RightKey();
        addObject(rightKey2,334,115);
        rightKey2.setLocation(344,108);
        removeObject(rightKey2);
        RightKey rightKey3 = new RightKey();
        addObject(rightKey3,313,116);
        rightKey3.setLocation(309,122);
        removeObject(rightKey3);
        RightKey rightKey4 = new RightKey();
        addObject(rightKey4,317,117);
        rightKey4.setLocation(325,134);
        removeObject(rightKey4);
        RightKey rightKey5 = new RightKey();
        addObject(rightKey5,341,119);
        FakeBeaver fakeBeaver = new FakeBeaver();
        addObject(fakeBeaver,228,122);
        removeObject(log);
        removeObject(rock);
        removeObject(stone);
        removeObject(whirlpool);
        removeObject(piranha);
        removeObject(cherry);
        removeObject(goldenCherry);
        Stone stone2 = new Stone();
        addObject(stone2,925,114);
        rock rock2 = new rock();
        addObject(rock2,747,113);
        Piranha piranha2 = new Piranha();
        addObject(piranha2,831,107);
        Log log2 = new Log();
        addObject(log2,834,172);
        Obstacles obstacles = new Obstacles();
        addObject(obstacles,769,35);
        removeObject(obstacles);
        Obstacles obstacles2 = new Obstacles();
        addObject(obstacles2,786,32);
        obstacles2.setLocation(788,48);
        obstacles2.setLocation(652,42);
        removeObject(obstacles2);
        Obstacles obstacles3 = new Obstacles();
        addObject(obstacles3,780,33);
        removeObject(obstacles3);
        Obstacles obstacles4 = new Obstacles();
        addObject(obstacles4,780,39);
        FakeLog fakeLog = new FakeLog();
        addObject(fakeLog,537,35);
        FakeLog fakeLog2 = new FakeLog();
        addObject(fakeLog2,537,104);
        FakeLog fakeLog3 = new FakeLog();
        addObject(fakeLog3,539,174);
        FakeLog fakeLog4 = new FakeLog();
        addObject(fakeLog4,538,241);
        FakeLog fakeLog5 = new FakeLog();
        addObject(fakeLog5,540,309);
        FakeLog fakeLog6 = new FakeLog();
        addObject(fakeLog6,541,376);
        FakeLog fakeLog7 = new FakeLog();
        addObject(fakeLog7,541,443);
        FakeLog fakeLog8 = new FakeLog();
        addObject(fakeLog8,542,511);
        Log log3 = new Log();
        addObject(log3,572,206);
        Log log4 = new Log();
        addObject(log4,643,206);
        Log log5 = new Log();
        addObject(log5,715,207);
        Log log6 = new Log();
        addObject(log6,788,205);
        Log log7 = new Log();
        addObject(log7,859,205);
        Log log8 = new Log();
        addObject(log8,933,204);
        removeObject(log2);
        FakeLog fakeLog9 = new FakeLog();
        addObject(fakeLog9,632,118);
        Log log9 = new Log();
        addObject(log9,498,204);
        Log log10 = new Log();
        addObject(log10,428,203);
        Log log11 = new Log();
        addObject(log11,351,202);
        Log log12 = new Log();
        addObject(log12,279,204);
        Log log13 = new Log();
        addObject(log13,204,204);
        Log log14 = new Log();
        addObject(log14,136,203);
        Log log15 = new Log();
        addObject(log15,65,204);
        log15.setLocation(28,203);
        Log log16 = new Log();
        addObject(log16,28,203);
        Log log17 = new Log();
        addObject(log17,987,204);
        fakeLog8.setLocation(542,544);
        FakeLog fakeLog10 = new FakeLog();
        addObject(fakeLog10,542,544);
        removeObject(log16);
        removeObject(log15);
        removeObject(log14);
        removeObject(log11);
        log10.setLocation(405,200);
        removeObject(log10);
        Log log18 = new Log();
        addObject(log18,428,203);
        removeObject(log18);
        Log log19 = new Log();
        addObject(log19,428,204);
        Log log20 = new Log();
        addObject(log20,352,203);
        removeObject(log20);
        Log log21 = new Log();
        addObject(log21,358,204);
        removeObject(log12);
        removeObject(log13);
        Log log22 = new Log();
        addObject(log22,287,205);
        Log log23 = new Log();
        addObject(log23,214,204);
        removeObject(log23);
        Log log24 = new Log();
        addObject(log24,216,204);
        removeObject(log24);
        Log log25 = new Log();
        addObject(log25,217,205);
        Log log26 = new Log();
        addObject(log26,145,204);
        Log log27 = new Log();
        addObject(log27,76,207);
        Log log28 = new Log();
        addObject(log28,26,206);
        removeObject(log27);
        Log log29 = new Log();
        addObject(log29,91,206);
        removeObject(log26);
        Log log30 = new Log();
        addObject(log30,146,205);
        removeObject(log29);
        removeObject(log28);
        Log log31 = new Log();
        addObject(log31,78,207);
        Log log32 = new Log();
        addObject(log32,33,207);
        removeObject(fakeLog10);
        removeObject(fakeLog8);
        FakeLog fakeLog11 = new FakeLog();
        addObject(fakeLog11,540,512);
        fakeLog11.setLocation(540,537);
        FakeLog fakeLog12 = new FakeLog();
        addObject(fakeLog12,540,537);
        removeObject(fakeLog12);
        removeObject(fakeLog11);
        FakeLog fakeLog13 = new FakeLog();
        addObject(fakeLog13,540,504);
        fakeLog13.setLocation(541,520);
        FakeLog fakeLog14 = new FakeLog();
        addObject(fakeLog14,541,520);
        removeObject(fakeLog14);
        fakeLog13.setLocation(540,485);
        FakeLog fakeLog15 = new FakeLog();
        addObject(fakeLog15,540,485);
        removeObject(fakeLog15);
        FakeLog fakeLog16 = new FakeLog();
        addObject(fakeLog16,540,543);
        log7.setLocation(887,204);
        GoldenCherry goldenCherry2 = new GoldenCherry();
        addObject(goldenCherry2,657,335);
        Cherry cherry2 = new Cherry();
        addObject(cherry2,788,330);
        log6.setLocation(822,204);
        Log log33 = new Log();
        addObject(log33,822,204);
        removeObject(log33);
        Log log34 = new Log();
        addObject(log34,769,204);
        Log log35 = new Log();
        addObject(log35,582,375);
        Log log36 = new Log();
        addObject(log36,650,374);
        Log log37 = new Log();
        addObject(log37,711,375);
        Log log38 = new Log();
        addObject(log38,776,372);
        Log log39 = new Log();
        addObject(log39,840,372);
        Log log40 = new Log();
        addObject(log40,904,372);
        Log log41 = new Log();
        addObject(log41,952,370);
        log37.setLocation(696,376);
        removeObject(log37);
        Log log42 = new Log();
        addObject(log42,712,374);
        removeObject(cherry2);
        removeObject(goldenCherry2);
        Cherry cherry3 = new Cherry();
        addObject(cherry3,682,316);
        GoldenCherry goldenCherry3 = new GoldenCherry();
        addObject(goldenCherry3,805,312);
        CherryPoints cherryPoints = new CherryPoints();
        addObject(cherryPoints,757,263);
        removeObject(cherryPoints);
        CherryPoints cherryPoints2 = new CherryPoints();
        addObject(cherryPoints2,764,250);
        goldenCherry3.setLocation(810,320);
        goldenCherry3.setLocation(814,318);
        Plus1 plus1 = new Plus1();
        addObject(plus1,732,316);
        Plus3 plus3 = new Plus3();
        addObject(plus3,880,320);
        removeObject(cherry3);
        removeObject(plus1);
        Cherry cherry4 = new Cherry();
        addObject(cherry4,621,312);
        Plus1 plus12 = new Plus1();
        addObject(plus12,682,312);
        removeObject(goldenCherry3);
        removeObject(plus3);
        GoldenCherry goldenCherry4 = new GoldenCherry();
        addObject(goldenCherry4,836,305);
        removeObject(goldenCherry4);
        GoldenCherry goldenCherry5 = new GoldenCherry();
        addObject(goldenCherry5,844,309);
        goldenCherry5.setLocation(842,316);
        Plus3 plus32 = new Plus3();
        addObject(plus32,900,316);
        goldenCherry5.setLocation(851,320);
        removeObject(goldenCherry5);
        GoldenCherry goldenCherry6 = new GoldenCherry();
        addObject(goldenCherry6,830,310);
        removeObject(goldenCherry6);

        addObject(goldenCherry6,833,313);
        removeObject(fakeLog9);
        FakeLog fakeLog17 = new FakeLog();
        addObject(fakeLog17,633,116);
        Whirlpool whirlpool2 = new Whirlpool();
        addObject(whirlpool2,216,420);
        WhirlpoolControls whirlpoolControls = new WhirlpoolControls();
        addObject(whirlpoolControls,295,256);
        removeObject(whirlpoolControls);
        WhirlpoolControls whirlpoolControls2 = new WhirlpoolControls();
        addObject(whirlpoolControls2,269,251);
        removeObject(fakeLog5);
        removeObject(whirlpoolControls2);
        removeObject(fakeLog6);
        removeObject(fakeLog7);
        removeObject(fakeLog13);
        removeObject(fakeLog16);
        removeObject(fakeLog4);
        removeObject(fakeLog3);
        removeObject(fakeLog2);
        removeObject(fakeLog);
        FakeLog fakeLog18 = new FakeLog();
        addObject(fakeLog18,561,39);
        FakeLog fakeLog19 = new FakeLog();
        addObject(fakeLog19,561,105);
        FakeLog fakeLog20 = new FakeLog();
        addObject(fakeLog20,561,173);
        FakeLog fakeLog21 = new FakeLog();
        addObject(fakeLog21,562,242);
        FakeLog fakeLog22 = new FakeLog();
        addObject(fakeLog22,564,309);
        log35.setLocation(564,377);
        FakeLog fakeLog23 = new FakeLog();
        addObject(fakeLog23,564,377);
        FakeLog fakeLog24 = new FakeLog();
        addObject(fakeLog24,563,442);
        FakeLog fakeLog25 = new FakeLog();
        addObject(fakeLog25,564,509);
        FakeLog fakeLog26 = new FakeLog();
        addObject(fakeLog26,564,553);
        removeObject(log35);
        Log log43 = new Log();
        addObject(log43,592,375);
        WhirlpoolControls whirlpoolControls3 = new WhirlpoolControls();
        addObject(whirlpoolControls3,269,255);
        removeObject(whirlpool2);
        Whirlpool whirlpool3 = new Whirlpool();
        addObject(whirlpool3,202,352);
        Whirlpool whirlpool4 = new Whirlpool();
        addObject(whirlpool4,351,350);

        ReachEnd reachEnd = new ReachEnd();
        addObject(reachEnd,719,450);
        removeObject(reachEnd);
        ReachEnd reachEnd2 = new ReachEnd();
        addObject(reachEnd2,726,447);

        EndLevel3 endLevel3 = new EndLevel3();
        addObject(endLevel3,903,468);
        removeObject(endLevel3);

        addObject(endLevel3,901,468);
        removeObject(whirlpool3);
        removeObject(whirlpool4);
        Whirlpool whirlpool5 = new Whirlpool();
        addObject(whirlpool5,119,378);
        Whirlpool whirlpool6 = new Whirlpool();
        addObject(whirlpool6,344,373);
        removeObject(whirlpool5);
        Whirlpool whirlpool7 = new Whirlpool();
        addObject(whirlpool7,127,372);
        removeObject(whirlpool6);
        removeObject(whirlpool7);
        Whirlpool whirlpool8 = new Whirlpool();
        addObject(whirlpool8,141,376);
        Whirlpool whirlpool9 = new Whirlpool();
        addObject(whirlpool9,387,375);
        whirlpoolControls3.setLocation(236,271);
        removeObject(whirlpoolControls3);
        WhirlpoolControls whirlpoolControls4 = new WhirlpoolControls();
        addObject(whirlpoolControls4,274,267);
        whirlpool8.setLocation(160,372);
        removeObject(whirlpool8);
        removeObject(whirlpool9);
        Whirlpool whirlpool10 = new Whirlpool();
        addObject(whirlpool10,151,380);
        Whirlpool whirlpool11 = new Whirlpool();
        addObject(whirlpool11,384,378);
  
        BackTutorial backTutorial = new BackTutorial();
        addObject(backTutorial,84,521);
    }
}
